title:              Isaac Lee Blog
email:              yy0221ss@gmail.com
description:        A Blog Theme by Start Bootstrap
author:             Start Bootstrap
baseurl:            "/Isaac-Lee/"
url:                "https://Isaac-Lee.github.io"

# Social Profiles
twitter_username:   SBootstrap
github_username:    BlackrockDigital
facebook_username:  이예성(Isaac Lee)
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
